host: "proddbgo.example.com"
port: 1521
service_name: "ORCL"
default_schema: "MYSCHEMA"
oracle_client:
  instant_client_dir: "/path/to/instantclient"
  krb5_conf: "/path/to/krb5.conf"
  krb5_cache: "/path/to/krb5cc"
  trace_level: 16
  trace_directory: "/path/to/trace"